# https://github.com/docker/whalesay/tree/master
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world-script
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
spec:
  entrypoint: hello-script
  volumes:
  # Pass my-existing-volume as an argument to the volumes-existing-example template
  # Same syntax as k8s Pod spec
  - name: workdir
    persistentVolumeClaim:
      claimName: my-existing-volume

  templates:
    - name: hello-script
      container:
        image: khanhph/helloscript:latest
        command: [main]
        args: ["khanhph4xx"]
        volumeMounts:                     # same syntax as k8s Pod spec
        - name: workdir
          mountPath: /home/khanhph4/docker/docker-build

